version: 0.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget.exe restore Waterworks.sln
build:
  project: Waterworks.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: NuGet/Release/Waterworks.*.nupkg